version: '3.4'

networks:
  appnetwork:

services:
    webapidb:
        container_name: sqlserver2019db
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
             - "8002:1433"
        environment:
            ACCEPT_EULA : y
            SA_PASSWORD: Pa55W0rd!
        networks: 
            appnetwork:
                aliases:
                    - sqlserver2019db
    webapentityframeworkdocker:
        container_name: web_api_application
        image: ${DOCKER_REGISTRY-}webapentityframeworkdocker
        build: 
            context: .
            dockerfile: webapentityframeworkdocker/Dockerfile
        ports:
            - "8001:80"
        depends_on:
            -  webapidb
        networks: 
            - appnetwork

